services:
  eureka-server:
    container_name: eureka-server
    image: luisenriquesm/eureka:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
      
  msvc-products:
    container_name: msvc-products
    image: luisenriquesm/products:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql8
      - eureka-server

  msvc-items:
    container_name: msvc-items
    image: luisenriquesm/items:v2
    ports:
      - "8005:8005"
    restart: always
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - msvc-products
     
networks:
  springcloud: