services:
  eureka-server:
    container_name: eureka-server
    image: luisenriquesm/eureka:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql8:
    container_name: mysql8
    image: mysql:8.0.42
    ports:
      - "3306:3306"
    restart: always
    networks:
      - springcloud
    environment:
      - MYSQL_DATABASE=db_springboot_cloud
      - MYSQL_ROOT_PASSWORD=sasa1234

  msvc-products:
    container_name: msvc-products
    image: luisenriquesm/products:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql8
      - eureka-server

  msvc-items:
    container_name: msvc-items
    image: luisenriquesm/items:v2
    ports:
      - "8005:8005"
    restart: always
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - msvc-products
     
networks:
  springcloud: